---


'.review':
  script:
    - 'export TOXENV="${CI_JOB_NAME##review}"'
    - 'python -m pip install tox'
    - 'python -m tox'
    - 'python -m tox -e package'

'review py38':
  extends: '.review'
  image: 'python:3.8'

'review py39':
  extends: '.review'
  image: 'python:3.9'

'review py310':
  extends: '.review'
  image: 'python:3.10'

'review py311':
  extends: '.review'
  image: 'python:3.11'

'review py312':
  allow_failure: true
  extends: '.review'
  image: 'python:3.12-rc'


...  # EOF
